# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "dev" do |web|
    web.vm.box = "debian/jessie64"
	config.vm.network :forwarded_port, guest: 80, host: 80
	config.vm.network :forwarded_port, guest: 3306, host: 3306
	config.vm.synced_folder "./src", "/var/www/html"
	config.vm.provider "virtualbox" do |virtualbox|
	  virtualbox.customize [ "modifyvm", :id, "--cpus", "2" ]
	  virtualbox.customize [ "modifyvm", :id, "--memory", "2048" ]
	end
	config.vm.provision "shell", path: "webserver.sh"
	config.vm.provision "shell", path: "database.sh"
  end
 
end
