version: '3'
services:
  database:
    image: mysql/mysql-server:8.0
    container_name: database-project
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    networks:
        - project-network

  application:
    build: configs/containers/php-7.4.30-fpm
    container_name: application-project
    hostname: application-project
    working_dir: /var/www/html
    depends_on:
        - database
    volumes:
        - ./application:/var/www/html
        - ./configs/web/php/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    networks:
        - project-network

  webserver:
    build: configs/containers/nginx
    container_name: webserver-project
    hostname: webserver-project
    depends_on:
        - application
    volumes:
        - ./application:/var/www/html
        - ./configs/web/sites-available/000-default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - "80:8000"
    networks:
        - project-network

networks:
    project-network:
        driver: bridge
