version: '2.1'
services:
  database:
    image: mysql/mysql-server:8.0
    container_name: database-project
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password --sql_mode=""
    networks:
        - project-network

  application:
    build: containers/php-7.4-fpm
    container_name: application-project
    hostname: application-project
    working_dir: /var/www/html
    depends_on:
        - database
    volumes:
        - ./containers/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        - ./application:/var/www/html
    networks:
        - project-network

  webserver:
    build: containers/nginx
    container_name: webserver-project
    hostname: webserver-project
    depends_on:
        - application
    volumes:
        - ./application:/var/www/html
    ports:
        - "80:80"
    networks:
        - project-network

volumes:
    db-data:

networks:
    project-network:
        driver: bridge
