image: php:7.4.11-fpm

stages:
    - build
    - test
    - deploy

composer:
    stage: build
    image: composer:latest
    before_script:
        - cd application
    script:
        - composer install
    artifacts:
        paths:
            - application/vendor

code-style:
    stage: test
    before_script:
        - cd application
    script:
        - php vendor/bin/phpcs --standard=phpcs.xml.dist

lint:
    stage: test
    before_script:
        - cd application
    script:
        - vendor/bin/parallel-lint -j 30 --exclude vendor .

teste-unitario:
    stage: test
    before_script:
        - cd application
    script:
        - php vendor/bin/phpunit tests/

develop:
    stage: deploy
    script:
        - echo "deploy em develop"
    only:
        - develop

master:
    stage: deploy
    script:
        - echo "deploy em master"
    only:
        - master
